        !COMPILER-GENERATED INTERFACE MODULE: Sat May 14 15:49:50 2016
        MODULE INITIAL_SI__genmod
          INTERFACE 
            SUBROUTINE INITIAL_SI
            END SUBROUTINE INITIAL_SI
          END INTERFACE 
        END MODULE INITIAL_SI__genmod
