        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 24 11:52:07 2017
        MODULE INITIAL__genmod
          INTERFACE 
            SUBROUTINE INITIAL
            END SUBROUTINE INITIAL
          END INTERFACE 
        END MODULE INITIAL__genmod
