        !COMPILER-GENERATED INTERFACE MODULE: Sat May 14 15:51:00 2016
        MODULE SGENRND__genmod
          INTERFACE 
            SUBROUTINE SGENRND
            END SUBROUTINE SGENRND
          END INTERFACE 
        END MODULE SGENRND__genmod
