        !COMPILER-GENERATED INTERFACE MODULE: Mon Aug 08 18:51:54 2016
        MODULE WRITECONFIG__genmod
          INTERFACE 
            SUBROUTINE WRITECONFIG
            END SUBROUTINE WRITECONFIG
          END INTERFACE 
        END MODULE WRITECONFIG__genmod
